# Generated by Django 5.0 on 2026-02-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
